apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "danscafedev"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "danscafedev"
    spec:
      containers:
        - name: "danscafedev"
          image: "danscafetestacr.azurecr.io/danscafedev"
          ports:
          - containerPort: 3001